name: Build and Upload APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd netmesh-android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # यहाँ मैंने पाथ को फ्लेक्सिबल कर दिया है ताकि वह किसी भी फोल्डर से APK उठा ले
          path: netmesh-android/app/build/outputs/apk/debug/*.apk
